instrumentation:
    root: .
    extensions:
        - .js
    default-excludes: true
    excludes: ['**/rosidl_parser/**', '**/src/**', '**/generated/**', '**/docs/**', '**/build/**', '**/scripts/**', '**/rosidl_gen/**']
