version: 2.1

orbs:
  sixrs-gke: sixriversystems/sixrs-gke@7

jobs:
  build:
    docker:
      - image: osrf/ros:iron-desktop
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command:  curl -o /tmp/nodejs.deb https://deb.nodesource.com/node_20.x/pool/main/n/nodejs/nodejs_20.15.1-1nodesource1_$(dpkg --print-architecture).deb && apt-get update && apt-get install -y /tmp/nodejs.deb
      - sixrs-gke/setup-private-npm
      - sixrs-gke/run-release
      - run:
          name: install
          command: source /opt/ros/iron/setup.bash && npm ci && npm publish
      - persist_to_workspace:
          root: ./
          paths:
            - .

  test:
    docker:
      - image: osrf/ros:iron-desktop
        environment:
          NODE_ENV: test
          CMAKE_PREFIX_PATH: /opt/ros/iron
          ROS_PACKAGE_PATH: /opt/ros/iron/share
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: setup node and run tests
          command: |
            sudo apt update &&\
            sudo apt install -q -y curl &&\
            curl -sL https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh -o ~/install_nvm.sh &&\
            bash ~/install_nvm.sh &&\
            echo "sourcing .profile" &&\
            source ~/.profile &&\
            echo "sourcing .bashrc" &&\
            source ~/.bashrc &&\
            curl -o /tmp/nodejs.deb https://deb.nodesource.com/node_20.x/pool/main/n/nodejs/nodejs_20.15.1-1nodesource1_$(dpkg --print-architecture).deb && apt-get update && apt-get install -y /tmp/nodejs.deb &&\
            npm run test

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: 6rs-circle
      - test:
          context: 6rs-circle
          requires:
            - build
