version: 2.1

orbs:
  sixrs-gke: sixriversystems/sixrs-gke@7

jobs:
  build:
    docker:
      - image: osrf/ros:iron-desktop
    steps:
      - checkout
      - sixrs-gke/setup-private-npm
      - run:
          name: Install Dependencies
          command:  curl -o /tmp/nodejs.deb https://deb.nodesource.com/node_20.x/pool/main/n/nodejs/nodejs_20.15.1-1nodesource1_$(dpkg --print-architecture).deb && apt-get update && apt-get install -y /tmp/nodejs.deb
      - sixrs-gke/run-release
      - run:
          name: install
          command: npm ci
      - persist_to_workspace:
          root: ./
          paths:
            - .

  publish:
    docker:
      - image: cimg/node:20.15.0
    steps:
      - attach_workspace:
          at: ./
      - sixrs-gke/setup-private-npm
      - run:
          name: npm publish
          command: npm publish
  test:
    docker:
      - image: ros:kinetic-ros-core-xenial
        environment:
          NODE_ENV: test
          CMAKE_PREFIX_PATH: /opt/ros/kinetic
          ROS_PACKAGE_PATH: /opt/ros/kinetic/share
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: setup node and run tests
          command: |
            sudo apt update &&\
            sudo apt install -q -y curl &&\
            curl -sL https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh -o ~/install_nvm.sh &&\
            bash ~/install_nvm.sh &&\
            echo "sourcing .profile" &&\
            source ~/.profile &&\
            echo "sourcing .bashrc" &&\
            source ~/.bashrc &&\
            echo "nvm setup done"
            echo "set env var" &&\
            export NVM_DIR="$HOME/.nvm" &&\
            echo "run nvm script" &&\
            source ~/.nvm/nvm.sh &&\
            echo "try install node" &&\
            echo "run bash completion" &&\
            source ~/.nvm/bash_completion &&\
            echo "install node" &&\
            nvm install 8.12.0 &&\
            echo "run tests" &&\
            npm run test

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: 6rs-circle
      # - test:
      #     context: 6rs-circle
      #     requires:
      #       - build
      - publish:
          context: 6rs-circle
          requires:
            - build
            # - test
